# Generated by Django 3.0.5 on 2020-04-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfoReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_plentific_job_number', models.CharField(max_length=7)),
                ('r_wo_number', models.IntegerField()),
                ('r_invoice_number_found', models.IntegerField()),
                ('r_payments', models.FloatField()),
                ('r_job_number_exists', models.CharField(max_length=3)),
            ],
        ),
    ]
