# Generated by Django 3.0.5 on 2020-04-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobinforeport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinforeport',
            name='r_payments',
            field=models.CharField(max_length=100),
        ),
    ]
