# Generated by Django 3.0.5 on 2020-04-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200421_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinforeport',
            name='r_invoice_number_found',
            field=models.CharField(max_length=5),
        ),
    ]
