# Generated by Django 3.0.5 on 2020-04-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200421_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinforeport',
            name='r_wo_number',
            field=models.CharField(max_length=6),
        ),
    ]
