# Generated by Django 3.0.5 on 2020-04-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200421_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinforeport',
            name='r_job_number_exists',
            field=models.CharField(max_length=50),
        ),
    ]
